### ISSUE TITLE
Feature request: Delete words from word cloud

### ISSUE THREAD

**Issue by mattgig** [elearning-univie/moodle-mod_wordcloud#1]
When using the activity in a class, the ability to delete words would be useful. The need for this might arise due to two different scenarios:

1) A user made a spelling mistake and wants to delete the entry (and maybe later replace it with a correct one).
2) A user entered an unappropriate word which the teacher wants to delete.

For the deletion interface, there are at least the following two possibilities:
1) On an additional page all the entries are listed and there you delete the expressions.
2) Deleting works directly in the graphical representation of the word cloud: When you click on a word, you can delete it (given you have the right to do so.)
While option 2 might be more intuitive, option 1 will probably be easier to implement and opens the possibility for bulk deletion further down the line.

**Comment by goggo24** [comment]
Thanks for your feedback. That's a good point. We will make a few thoughts ourselves based on your suggestions and keep you up-to-date.

**Comment by goggo24** [comment]
Update: we are just working on this feature - there will be a first solution for teachers do delete words.

**Comment by aczerzuh** [comment]
Implemented in v3.11.1
