### ISSUE TITLE
Feature request: Reset and Start/Stop-feature

### ISSUE THREAD

**Issue by Sindbad5** [elearning-univie/moodle-mod_wordcloud#2]
In advance of feature request „Delete“ I wonder if it could be possible to „Re-New“ the activity (Reset).
It’s possible to show/hide the activity. Complementary I think it could be a surplus value to start/stop the activity. So you can have a statue at stop-point - maybe over timer?

**Comment by goggo24** [comment]
Thanks for you feedback! You are right, that's a good idea. At the moment we are thinking of giving the teacher the opportunity to set a start or/and enddate for entering words (like the availability settings from assignment). We will put this issue in our backlog and will keep you up to date.

**Comment by Sindbad5** [comment]
Hi Eva,
Thanks for your answer!

It’s a tool which I will mostly use in live situations. So I would prefer a start-/stop-button because it is more easy to handle and flexible unlike a „configuration“ setting - which is also nice to have. Advanced would be a timer.

It could look like „E-Voting“ -Activity - maybe 🤔 

Best wishes and enjoy your weekend!
Marco Sauerhöfer

Idsteiner Str. 101
65193 Wiesbaden
Email ***@***.***
Festnetz +49 611 13700905
Mobil +49 170 298 12 93
===

**Comment by goggo24** [comment]
You could use context freezing in this situation. If the activity is freezed, nobody can write a word and defreeze it for writing statements. I know, it's not a start/stop button - but it's also only two click for teachers (gear icon => freeze this context).

**Comment by goggo24** [comment]
_Update:_ in our next version a start/enddate (like in assignment) will be available.

**Comment by aczerzuh** [comment]
Implemented in version v3.11.1
