### ISSUE TITLE
Feature request: Support for Moodle mobile App

### ISSUE THREAD

**Issue by Sindbad5** [elearning-univie/moodle-mod_wordcloud#3]
Is this possible?

**Comment by goggo24** [comment]
Thanks for your suggestion. We will discuss within our team how much work it is and than come back to you. If you can provide the code by yourself via pull request, we are willing to accept it ;)

**Comment by Sindbad5** [comment]
Hi Eva - back again 😉
It‘s more a question than a feature request. Sometimes depending on the „Live“-Situation it could be a plus.

Unfortunately, I don‘t have any experience in programming for the moodle mobile app - Sorry ☹️ 

Best wishes
Marco Sauerhöfer

Idsteiner Str. 101
65193 Wiesbaden
Email ***@***.***
Festnetz +49 611 13700905
Mobil +49 170 298 12 93
===

**Comment by goggo24** [comment]
Update: we are just working on this feature - it will be included in our next version.

**Comment by aczerzuh** [comment]
Implemented in version v3.11.1
