### ISSUE TITLE
Missing language string

### ISSUE THREAD

**Issue by mattgig** [elearning-univie/moodle-mod_wordcloud#4]
Deleting words from a word cloud now works nicely. However, the language string missing [[removeflashcard]] is missing in the feature or not properly translated.

![image](https://user-images.githubusercontent.com/7272764/164940639-5ef9baf9-4705-4478-ad0c-ca6b4a4f79d4.png)

Thanks for your great work.
Matthias

BTW, the plugin also works in Moodle 4.0.

**Comment by goggo24** [comment]
Thanks for reporting. We will fix it.

**Comment by aczerzuh** [comment]
Fixed in version v3.11.2
