### ISSUE TITLE
Feature Request: Show result of wordcloud only after time is over

### ISSUE THREAD

**Issue by hschnurbusch** [elearning-univie/moodle-mod_wordcloud#7]
Hi

Thank you for this nice little plugin. We're currently testing the wordcloud with some of our teachers. One feedback was that it would be nice to be able to hide the resulting wordcloud until your course participants have entered their words and time is over. This way they would not be influenced by what others are entering.

Thank you very much!
Harald

**Comment by v-r-n-a** [comment]
Hello,
I support the features request, we already use the plugin in a lot of courses, really good for different scenarios.
It'd be great to have Harald's suggestion as two different/independent features:

- Show result only after student submitted some words
- Show result after a schedulded time has passed

For asynchronous use, the first feature without a schedulded time would be of great value, for synchronous learning the latter would be a a helpful addition.
Best regards, verena

**Comment by mwreichel** [comment]
Hi @v-r-n-a ,
thank you for your further comment on that issue. We also thought of this two additional options for the visibility of words. :-)

Kind regards,
Martin

**Comment by mwreichel** [comment]
Hi,
sorry for my late answer to this issue. We already implemented this in plugin version 4.4.0 ;-)

All the best,
Martin
